spring.application.name=backend

# Cấu hình Database (Đã che mật khẩu)
# Render sẽ tự điền giá trị thật vào các biến ${...} này
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Cấu hình Upload (Sửa lại đường dẫn cứng ổ D để tránh lỗi trên Render)
app.upload.dir=${APP_UPLOAD_DIR}
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Cấu hình Cloudinary (Đã che key)
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}